import { Inter } from "next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GoogleFontsLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section className="w-full min-h-screen p-5">
      {/* Include shared UI here e.g. a header or sidebar */}
      <nav className="  p-5  flex flex-row justify-center border-orange-700">
        <div className="flex flex-row justify-between items-center flex-1 bg-red-200 px-4 py-2 min-w-8">
          <div className=" flex-1 bg-red-800 p-5 justify-center items-center flex">
            <p>Home Logo</p>
          </div>

          <div className="  flex-col  flex  flex-1">
            <ul className="flex justify-between flex-row  item-center">
              <li>
                <Link href={"/"}> Projects</Link>
              </li>
              <li>
                <Link href={"/"}> Contact</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {children}
    </section>
  );
}
